# Generated by Django 4.2.2 on 2023-07-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_copies_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies_book', to='books.book'),
        ),
    ]
