# Generated by Django 4.2.2 on 2023-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_copy_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
