# Generated by Django 4.2.2 on 2023-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_copy_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
