# Generated by Django 4.2.2 on 2023-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_copy_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quant_copies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
