# Generated by Django 4.2.2 on 2023-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_quant_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quant_copies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='quant_pag',
            field=models.PositiveIntegerField(),
        ),
    ]
