# Generated by Django 4.2.2 on 2023-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_quant_copies_alter_book_quant_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='number_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='quant_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='quant_pag',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
