# Generated by Django 4.2.2 on 2023-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_copy_number_received_alter_book_quant_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quant_copies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='quant_pag',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='copy',
            name='number_received',
            field=models.PositiveIntegerField(),
        ),
    ]
