# Generated by Django 4.2.2 on 2023-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_copy_number_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='number_received',
            field=models.PositiveIntegerField(),
        ),
    ]
