# Generated by Django 4.2.2 on 2023-06-30 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_exit', models.DateField(auto_now_add=True)),
                ('date_devolution', models.DateField(null=True)),
                ('returned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
