# Generated by Django 4.2.2 on 2023-07-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_copies_copy'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='copies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans_copy', to='books.copy'),
            preserve_default=False,
        ),
    ]
